---
# KADR will look for this file at ~/.kadr/config.yml
# Commented out options show their defaults. The others are required.

# Timeout for cached file information in seconds.
# cache_timeout_file: 1036800 # 12 days

# Timeouts for cached mylist information in seconds.
# A separate timeout can be set for anime which have unwatched episodes.
# cache_timeout_mylist_unwatched: 7200 # 2 hours
# cache_timeout_mylist_watched: 1036800 # 12 days

# Collation to use for filenames.
# A purely aesthetic option that only affects processing order.
# It has a small startup time penalty when enabled.
#
# Options:
#   none:      No sorting
#   ascii:     Case-sensitive alphabetical
#   ascii-i:   Case-insensitive alphabetical
#   auto:      unicode-i if Unicode::Collate is installed, otherwise ascii-i
#   unicode-i: Case-insensitive multi-lingual aware
#
# collator: auto

# Database where state information is kept.
# database: ~/.kadr/db

# A list of directories to index.
dirs_to_scan:
  - /Volumes/Yuuhi/Anime/Add
  - /Volumes/Yuuhi/HexChat/downloads/done
  - /Volumes/Yuuhi/Anime/Unwatched
  - /Volumes/Yuuhi/Anime/Watching
  - /Volumes/Yuuhi/Anime/Watched

# Empty directories are left behind when moving things.
# By default, all empty directories in dirs_to_scan are removed.
# delete_empty_dirs_in_scanned: 1

# Where to place unwatched episodes when found in a directory for watched episodes.
dir_to_put_unwatched_eps: /Volumes/Yuuhi/Anime

# Where to place watched episodes when found in a directory for unwatched episodes.
dir_to_put_watched_eps: /Volumes/Yuuhi/Anime

# The entire state database is loaded into memory on startup by default.
# This can be much faster when no AniDB queries are needed.
# Disable if the memory usage is more important than speed.
# load_local_cache_into_memory: 1

# The template for naming your files.
# See https://metacpan.org/module/Text::Xslate::Syntax::Kolon for how to use
# the templating language.
#
# TODO: documentation of the available fields
#
file_naming_scheme: |
  : if $anime.watched && !$episode.watched {
  Watching/
  :   if !$anime.is_ongoing { print 'Ongoing' }
  :   else { print 'Finished' }
  /
  : } else {
  :   if $episode.watched { print 'Watched' }
  :   else { print 'Unwatched' }
  /<: $anime.type :>/
  :   if $anime.type == 'TV Series' {
  :     if $anime.is_ongoing {
  Ongoing/
  :     } else {
  <: $anime.season_year :>/
  :     }
  :   }
  : }
  <: $anime.romaji_name :>/
  <: $anime.kanji_name :>
  : if $is_primary_episode {
  :   if $file_version > 1 { print ' v' ~ $file_version }
  : } else {
   - <: $episode.number :>
  :   if $file_version > 1 { print 'v' ~ $file_version }
  :   if $anime.total_episodes && !$episode.is_special {
  :     print '/' ~ $anime.total_episodes
  :   }
  :   if ($episode.kanji_name || $episode.english_name) != '' && $eid != 35113 && $aid != 6082 {
   - <: $episode.kanji_name || $episode.english_name :>
  :   }
  : }
  : if $group_short_name != 'raw' { print ' [' ~ $group_short_name ~ ']' }
  : if $video_resolution != '0x0' {
  [<: $source :> <: $video_resolution :> <: $video_codec :> <: $audio_codec :>]
  : }
  .<: $file_type :>

# Timeout for AniDB queries.
# query_timeout: 15.0

# Hashing progress display can be disabled. Not really useful anymore.
# show_hashing_progress: 1

# Enable to set the state of missing file to "deleted" on AniDB.
update_anidb_records_for_deleted_files: 1

# A list of directories where unwatched episodes are allowed to be.
valid_dirs_for_unwatched_eps:
  - /Volumes/Yuuhi/Anime/Unwatched
  - /Volumes/Yuuhi/Anime/Watching

# A list of directories where watched episodes are allowed to be.
valid_dirs_for_watched_eps:
  - /Volumes/Yuuhi/Anime/Watched

# Replace characters windows can't display.
# This is set by default when running on windows.
windows_compatible_filenames: 1
